require("config.launch")
require("config.options")
require("config.keymaps")
require("sam.autocmds")

spec("sam.autopairs")
spec("sam.cmp")
-- spec("sam.colorizer")
-- spec("sam.copilot")
spec("sam.colorscheme")
spec("sam.easy-align")
spec("sam.gitsigns")
spec("sam.harpoon")
spec("sam.indentline")
spec("sam.lspconfig")
spec("sam.mini")
spec("sam.markdown")
spec("sam.mason")
spec("sam.neotree")
spec("sam.none-ls")
spec("sam.oil")
spec("sam.symbols-outline")
spec("sam.telescope")
spec("sam.todo-comments")
spec("sam.toggleterm")
spec("sam.treesitter")
spec("sam.undotree")
-- spec("sam.whichkey")

require("config.lazy")
