require "config.launch"
require "config.options"
require "config.keymaps"
require "sam.autocmds"

spec "sam.animate"
spec "sam.autopairs"
spec "sam.breadcrumbs"
spec "sam.bufferline"
spec "sam.cmp"
spec "sam.colorizer"
spec "sam.colorscheme"
spec "sam.comment"
spec "sam.easy-align"
spec "sam.flash"
spec "sam.gitsigns"
spec "sam.harpoon"
spec "sam.illuminate"
spec "sam.indentline"
spec "sam.lspconfig"
spec "sam.lualine"
spec "sam.markdown"
spec "sam.mason"
spec "sam.neogen"
spec "sam.none-ls"
spec "sam.nvim-surround"
spec "sam.oil"
spec "sam.symbols-outline"
spec "sam.telescope"
spec "sam.todo-comments"
spec "sam.toggleterm"
spec "sam.treesitter"
spec "sam.undotree"
spec "sam.whichkey"


require "config.lazy"
