require "sam.launch"
require "sam.options"
require "sam.keymaps"
require "sam.autocmds"

spec "sam.colorscheme"
spec "sam.treesitter"
spec "sam.whichkey"
spec "sam.telescope"
spec "sam.harpoon"
spec "sam.lualine"
spec "sam.bufferline"
spec "sam.breadcrumbs"
spec "sam.none-ls"
-- spec "sam.copilot"
-- spec "sam.chatgpt"
spec "sam.mason"
spec "sam.nvim-surround"
spec "sam.neogit"
spec "sam.neotest"
spec "sam.gitsigns"
spec "sam.comment"
spec "sam.todo-comments"
spec "sam.autopairs"
spec "sam.indentline"
spec "sam.navic"
spec "sam.illuminate"
spec "sam.toggleterm"
spec "sam.cmp"
spec "sam.lspconfig"
spec "sam.undotree"
spec "sam.oil"
spec "sam.markdown"
spec "sam.colorizer"
-- spec "sam.mini"



require "sam.lazy"
